branch-defaults:
  master:
    environment: aws-eb-typescript-deployment-dev
global:
  application_name: aws-eb-typescript-deployment
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  sc: git
