version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - add_ssh_keys:
                fingerprints:
                  - "5b:9c:18:98:e5:ac:bc:61:29:a5:2f:8a:45:41:24:f9"
            - run: npm run clean
            - run: npm run build
            - run: npm run dist
            - run: git config user.email "dosemwegie@gmail.com"
            - run: git config user.name "David Osemwegie"
            - run: git add .
            - run: git commit -m "Rebuild [skip ci]"
            - run: git push
            - run: sudo apt-get -y -qq update
            - run: sudo apt-get install python-pip python-dev build-essential
            - run: sudo pip install --upgrade setuptools
            - run: sudo pip install awsebcli --upgrade
            - run: eb deploy aws-eb-typescript-deployment-dev
workflows:
  build-and-test:
    jobs:
      - build-and-test
