# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   install-eb:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - run:
#         name: "Installing deployment dependencies"
#         command: |
#           sudo apt-get -y -qq update
#           sudo apt-get install python-pip python-dev build-essential
#           sudo pip install --upgrade setuptools
#           sudo pip install awsebcli --upgrade
#       - run:
#         name: Deploying
#         command: eb deploy aws-eb-typescript-deployment-dev

# workflows:
#   deploy:
#     jobs:
#       - install-eb

version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo apt-get -y -qq update
            - run: sudo apt-get install python-pip python-dev build-essential
            - run: sudo pip install --upgrade setuptools
            - run: sudo pip install awsebcli --upgrade
            - run: eb deploy aws-eb-typescript-deployment-dev
workflows:
  build-and-test:
    jobs:
      - build-and-test
